In [111]:
import numpy as np


# Creating a 1D array

In [117]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# Creating a 2D array

In [129]:
arr_2d = np.array([[1, 2, 3],[ 4, 5, 6]])
print(arr_2d)


[[1 2 3]
 [4 5 6]]


# Array attributes: shape, dimesnions, size and data type
## arr.shape  Returns the shape of the array
## arr.ndim   Returns the number of dimensions
## arr.size   Returns the total number of elements
## arr.dtype # Returns the data type of elements

In [133]:
print(arr_2d.shape)

(2, 3)


In [135]:
print(arr_2d.ndim)

2


In [137]:
arr.size

5

In [139]:
arr.dtype

dtype('int64')

# Array indexing and slicing

In [ ]:
# print the first element of arr

In [ ]:
# print all elemenst second onwards

In [ ]:
# print the element in the second row and third column


In [ ]:
print(arr_2d[1,2])
print(arr_2d[0:2, 1:3])      

In [ ]:
# print elements in arr_2d: first three rows and second to fourth column

# Universal functions

In [ ]:
np.sqrt(arr)
np.exp(arr)

# aggregation functions

In [ ]:
mean = np.mean(arr)
std = np.std(arr)
arr_max = np.max(arr)


In [ ]:
print(f"Array is {arr}", f"; Mean is {mean}", f"std. deviation is {std}", f"Max value is {arr_max}" )

# Linear Algebra
## DOt product


In [ ]:
np.dot(arr, arr)

## Matrix Multiplication

In [ ]:
matrix1 = np.array([ [1,2],[3,4]])
matrix2 = np.array([ [5,6],[7,8]])
np.matmul(matrix1, matrix2)

## Eigenvalues and EIgendecomposition

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(matrix1)

In [ ]:
print(eigenvalues, eigenvectors)

## Random Number Generation

In [ ]:
np.random.rand(5) # array of 5 random numbers between 0 and 1

## Random Integers

In [ ]:
np.random.randint(0, 10, size=5) #  array of 5 random integers between 0 and 10

## Reshaping Arrays

In [145]:
arr = np.arange(12)
arr_reshaped = arr.reshape((1, 3, 4))  # Reshape to 3x4 array
print(arr)
print(arr_reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


## Flattening arrays

In [147]:
arr_flat = arr_reshaped.flatten()

In [149]:
print(arr_flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## Broadcasting

In [ ]:
arr = np.array([1, 2, 3])
result = arr + np.array([10])  # Broadcasting the addition
print(result)

## Broadcatsing with a scalar

In [151]:
# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Add a scalar value to each element of the array
result = array + 10

print("Original Array:")
print(array)
print("\nArray after adding scalar 10:")
print(result)


Original Array:
[[1 2 3]
 [4 5 6]]

Array after adding scalar 10:
[[11 12 13]
 [14 15 16]]


## Broadcasting with different shaped arrays

In [163]:
# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1D array
array_1d = np.array([10, 20, 30])

# Add the 1D array to the 2D array
result = array_2d + array_1d

print("2D Array:")
print(array_2d)
print("\n1D Array:")
print(array_1d)
print("\nResult after broadcasting:")
print(result)


2D Array:
[[1 2 3]
 [4 5 6]]

1D Array:
[10 20 30]

Result after broadcasting:
[[11 22 33]
 [14 25 36]]


## Broadcasting with higher dimensions 

In [157]:
# Create a 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Create a 2D array
array_2d = np.array([[1, 0, 1]])

# Add the 2D array to the 3D array
result = array_3d + array_2d

print("3D Array:")
print(array_3d)
print("\n2D Array:")
print(array_2d)
print("\nResult after broadcasting:")
print(result)


3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

2D Array:
[[1 0 1]]

Result after broadcasting:
[[[ 2  2  4]
  [ 5  5  7]]

 [[ 8  8 10]
  [11 11 13]]]


In [159]:
print(array_3d.shape)

(2, 2, 3)


In [161]:
print(array_2d.shape)

(1, 3)
